name: MsSql Nuget Package Upload

on:
  push:
    tags:
      - 'test*'

jobs:
  deploy:
    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'mssql.sln'
    
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mssql

    steps:
    - uses: actions/checkout@v2
    - uses: NuGet/setup-nuget@v1.0.5
    - name: Restore dependencies
      run: |
        nuget restore $SOLUTION
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Build
      run: dotnet build $SOLUTION --configuration $BUILD_CONFIG --no-restore
    - name: Run tests
      run: dotnet test /p:Configuration=$env:BUILD_CONFIG --no-restore --no-build --verbosity normal
