name: Redis Nuget Package Upload

on:
  push:
    tags:
      - 'redis*'

jobs:
  deploy:
    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'redis.sln'
    
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: redis

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - uses: NuGet/setup-nuget@v1.0.5
    - name: Restore dependencies
      run: |
        nuget restore $SOLUTION
    - name: Build
      run: dotnet build $SOLUTION --configuration $BUILD_CONFIG --no-restore
    - name: Publish
      run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
